config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :rooms do
    resource :messages
  end
  # Defines the root path route ("/")
  root "rooms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    load_room
    build_message
  end

  def create
    load_room
    build_message
    save_message or render 'new'
  end


  private

  def load_room
    @room = Room.find(params[:room_id])
  end

  def build_message
    @message ||= message_scope.build
    @message.attributes = message_params
  end

  def save_message
    if @message.save
      redirect_to @room
    end
  end

  def message_scope
    @room.messages
  end

  def message_params
    message_params = params[:message]
    message_params ? message_params.permit(:content) : {}
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    load_rooms
  end

  def show
    load_room
  end

  def new
    build_room
  end

  def create
    build_room
    save_room or render 'new'
  end

  def edit
    load_room
    build_room
  end

  def update
    load_room
    build_room
    save_room or render 'edit'
  end

  private
  def load_rooms
    @rooms = room_scope
  end

  def build_room
    @room ||= room_scope.build
    @room.attributes = room_params
  end

  def load_room
    @room ||= room_scope.find(params[:id])
  end

  def save_room
    if @room.save
      redirect_to @room
    end
  end

  def room_scope
    Room.all
  end

  def room_params
    room_params = params[:room]
    room_params ? room_params.permit(:name) : {}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_version.html.slim
p.server_meta
  | Version: #{APP_VERSION}

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | HotwireBlog
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css"
    = javascript_importmap_tags
  body
    = yield
    footer
      = render 'layouts/version'
      

app/views/messages/_message.html.slim
p.message id="#{dom_id(message)}"
  | 
    #{message.created_at.to_formatted_s(:short)}:
    #{message.content}

app/views/messages/new.html.slim
h1 New message

= form_for [@room, @message] do |f|
  = f.text_field :content
  .actions= f.submit

 

app/views/rooms/_form.html.slim
= form_for room do |f|
  - if @room.errors.any?
    #error_explanation
      h2 = "#{pluralize(@room.errors.count, 'error')} prohibited this room from being saved:"
      ul
        - @room.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/rooms/edit.html.slim
h1 Edit Room

= render 'form', room: @room

= link_to 'Show', @room
= link_to 'Back', rooms_path

app/views/rooms/index.html.slim
.rooms
  h1 Rooms

= link_to 'New', new_room_path

app/views/rooms/new.html.slim
h1 New Room

= render 'form', room: @room

app/views/rooms/show.html.slim
- room = @room
div.room id="#{dom_id(room)}"
  h1 
    |
      Room:
    span.room__name<= room.name

  / p
  /   strong Posted:
  /   =< time_tag room.created_at, "data-local": "time-ago" 

  / p
  /   strong= pluralize room.messages.count, "message" 

  #messages
    strong Messages:
    == render room.messages

  => link_to 'Show', room
  =< link_to 'Edit', edit_room_path(room)
  =< link_to 'Back', rooms_path
  =< link_to 'Destroy', room, data: { confirm: 'Are you sure?' }, method: :delete

= link_to 'New Message', new_room_messages_path(room)